config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  resources :flights, only: :index
  resources :bookings, only: [:new, :create, :show]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights,
    class_name: "Flight",
    foreign_key: :departure_airport_id, 
    dependent: :destroy

  has_many :arriving_flights, 
    class_name: "Flight", 
    foreign_key: :arriving_airport_id,
    dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"

  has_many :bookings, dependent: :destroy
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates :name,  presence: { message: "You need to specify a name for your passenger." }
  validates :email, presence: { message: "You need to specify an email for your passenger." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @flight = Flight.find(params[:choosen_flight])
    params[:number_of_passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      flash[:success] = "You've successfully booked tickets for this flight."
      redirect_to @booking
    else
      flight = Flight.find(params[:booking][:flight_id])
      render :new, assigns: { flight: flight },
                   status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id,
                                    passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = airports_formatted_collection
    @departure_dates = departure_dates_formatted_collection

    @flights = find_flights(params[:departure_airport], params[:arrival_airport], params[:departure_date])
  end

  private

  def airports_formatted_collection
    Airport.all.map { |a| [a.code, a.id] }
  end
  
  def departure_dates_formatted_collection
    Flight.select(:departure_date)
          .distinct
          .order(:departure_date)
          .map { |f| f.departure_date }
  end

  def find_flights(departure_airport, arrival_airport, departure_date)
    flights = Flight.all
    flights = flights.where(departure_airport: departure_airport) if departure_airport.present?
    flights = flights.where(arrival_airport: arrival_airport) if arrival_airport.present?
    flights = flights.where(departure_date: departure_date) if departure_date.present?
    flights
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Complete booking</h1>
<%= simple_form_for @booking do |f| %>
  <div><%= @flight.departure_airport.code %> ------------> <%= @flight.arrival_airport.code %></div>
  <div>On <%= @flight.departure_date %> at <%= @flight.departure_time %></div>
  <div>Flight id: <%= @flight.id %></div>
  <br>
  <%= f.input :flight_id, as: :hidden, input_html: { value: @flight.id } %>

  <div>Passengers:</div>
  <br>
  <%= f.simple_fields_for :passengers do |passengers_form| %>
    <%= passengers_form.input :name %>
    <br>
    <%= passengers_form.input :email %>
  <% end %>
  <br>
  <%= f.button :submit, "Book flight" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking #<%= @booking.id %></h1>

<div><%= @booking.flight.departure_airport.code %> ------------> <%= @booking.flight.arrival_airport.code %></div>
<div>On <%= @booking.flight.departure_date %> at <%= @booking.flight.departure_time %></div>
<br>
<div>Passengers:</div>
<ol>
  <% @booking.passengers.each do |passenger| %>
    <li><%= passenger.name %> (<%= passenger.email %>)</li>
  <% end %>
</ol>

app/views/flights/index.html.erb
<%= form_with url: flights_path, method: :get do |f| %>
  <div style="display: flex; gap: 20px; align-items: center">
    <div>
      <%= f.label :departure_airport, "Departure airport:" %>
      <%= select_tag(:departure_airport,
                     options_for_select(@airports,
                                       selected: params[:departure_airport]),
                                       include_blank: true) %>
    </div>
    <div>
      <%= f.label :arrival_airport, "Arrival airport:" %>
      <%= select_tag(:arrival_airport,
                     options_for_select(@airports,
                                        selected: params[:arrival_airport]),
                                        include_blank: true) %>
    </div>
    <div>
      <%= f.label :number_of_passengers, "Number of passengers:" %>
      <%= select_tag(:number_of_passengers,
                     options_for_select(1..4,
                                        selected: params[:number_of_passengers])) %>
    </div>
    <div>
      <%= f.label :departure_date, "Departure date:" %>
      <%= select_tag(:departure_date, 
                     options_for_select(@departure_dates,
                                        selected: params[:departure_date]),
                                        include_blank: true) %>
    </div>
    <%= f.submit "Search" %>
  </div>
<% end %>

<% if params[:departure_airport] || params[:arrival_airport] %>
  <div>Search results:</div>

  <% unless @flights.empty? %>
  
    <%= form_with url: new_booking_path, method: :get do |f| %>
      <% @flights.each do |flight| %>
        <div style="display: flex; gap: 20px; margin: 15px; border: 1px solid black; padding: 10px; border-radius: 3px">
          <%= radio_button_tag("choosen_flight", flight.id) %>
          <label for="choosen_flight_<%= flight.id %>">
            <div>Departure airport: <%= flight.departure_airport.code %></div>
            <div>Arrival airport: <%= flight.arrival_airport.code %></div>
            <div>Departure date: <%= flight.departure_date %></div>
            <div>Departure time: <%= flight.departure_time %></div>
          </label>
        </div>
      <% end %>
      <%= f.hidden_field :number_of_passengers, value: params[:number_of_passengers] %>
      <%= f.submit "Book choosen flight" %>
    <% end %>

  <% else %>
    <div>No flights were found.</div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      *, *::before, *::after {
        box-sizing: border-box;
      }

      body {
        line-height: 1.5;
        -webkit-font-smoothing: antialiased;
        font-family: "inter", "noto sans jp";
      }

      img, picture, video, canvas, svg {
        display: block;
        max-width: 100%;
      }

      input, button, textarea, select {
        font: inherit;
      }

      p, h1, h2, h3, h4, h5, h6 {
        overflow-wrap: break-word;
      }

      #root, #__next {
        isolation: isolate;
      }

      .input {
        display: flex;
        gap: 20px;
      }
    </style>
  </head>

  <body>
    <p class="success"><%= flash[:success] %></p>

    <%= yield %>
  </body>
</html>